[project]
name = "ASCIICrafter"
authors = [{name = "Graziella", email = "spaceartisan@gmail.com"}]
dynamic = ["version", "description"]
dependencies = [
    "Console",
    "World",
    "Object",
    "Entities"
]
